version: "3.0"
services:

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=muffin-wallet
      - POSTGRES_PASSWORD=muffin-wallet
      - POSTGRES_DB=muffin_wallet
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      dockerfile: Dockerfile
      args:
        JAR_FILE: muffin-wallet-server/build/libs/muffin-wallet-server-1.0.0.jar
    ports:
      - 8081:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/muffin_wallet
      SPRING_DATASOURCE_PASSWORD: muffin-wallet
      SPRING_DATASOURCE_USERNAME: muffin-wallet
      CURRENCY_SERVICE_URL: http://second:8080/rate
      # Лог-файл теперь находится в общем томе
      LOGGING_FILE_NAME: /var/log/app.log
    volumes:
      - logs:/var/log

  nginx:
    image: nginx
    depends_on:
      - app
    volumes:
      - logs:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80

  second:
    image: aadan1lov/muffin-currency:1.0.0

volumes:
  logs: