server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: app-logs
    pipeline_stages:
      - regex:
          expression: '\[(?P<traceId>[a-f0-9]+),(?P<spanId>[a-f0-9]+)\]'
      - labels:
          traceId: 
    static_configs:
      - targets:
          - localhost
        labels:
          job: myapp
          __path__: /var/log/app/**/*.log