apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  strategy:
    type: {{ .Values.deployment.strategy.type }}
    {{- if eq .Values.deployment.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.deployment.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.deployment.strategy.rollingUpdate.maxUnavailable }}
    {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
#      serviceAccountName: {{ .Values.deployment.serviceAccount }}
      volumes:
        - name: {{ .Values.app.applicationConfigVolume}}
          configMap:
            name: {{ .Values.app.applicationConfigVolume}}
        - name: logs-volume
          emptyDir: { }
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: JDK_JAVA_OPTIONS
              value: {{ .Values.app.jdkJavaOptions}}
            - name: DB_URL
              value: {{ .Values.app.jdbcUrl }}
            - name: DB_USERNAME
              value: {{ .Values.app.dbUsername}}
            - name: DB_PASSWORD
              value: {{ .Values.app.dbPassword }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          volumeMounts:
            - name: {{ .Values.app.applicationConfigVolume}}
              mountPath: /app/config
            - name: logs-volume
              mountPath: /logs
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        - name: alloy-sidecar
          image: grafana/alloy:latest
          volumeMounts:
            - name: logs-volume
              mountPath: /logs
          command: ["/bin/sh", "-c"]
          args:
            - |
              cat > /tmp/alloy.config << 'EOF'
              loki.source.file "app_logs" {
                targets = [
                  { __path__ = "/logs/app.log" },
                ]
                forward_to = [loki.process.add_all_labels.receiver]
              }
              loki.process "add_all_labels" {
                forward_to = [loki.write.to_loki.receiver]
                stage.static_labels {
                  values = {
                    app = "muffin-wallet",
                  }
                }
                stage.regex {
                  expression = ".*(?P<json>{.*})$"
                }
                stage.json {
                  expressions = {
                    level      = "level",
                    method     = "method",
                    path       = "path",
                    status     = "status",
                  }
                }
                stage.labels {
                  values = {
                    level       = "",
                    method      = "",
                    path        = "",
                    status      = "",
                  }
                }
              }
              loki.write "to_loki" {
                endpoint {
                  url = "http://loki-stack:3100/loki/api/v1/push"
                }
              }
              EOF
              exec /bin/alloy run /tmp/alloy.config