---

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/muffin_wallet
    username: muffin-wallet
    password: muffin-wallet

logging:
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"

currency:
  service:
    url: http://localhost:8080/rate

logging.file.name: logs/app.log
management:
  tracing:
    sampling:
      probability: 1.0 # Sample 100% of traces for demo
  zipkin:
    endpoint: "http://localhost:9411/api/v2/spans" # Zipkin's v2 API
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

management.metrics.distribution.percentiles-histogram.http.server.requests: true