apiVersion: v2
name: muffin-currency
description: A Helm chart for Muffin Currency service
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: viktoriuss
keywords:
  - muffin
  - currency

