replicaCount: 1

image:
  repository: haleen/muffin-currency
  pullPolicy: IfNotPresent
  tag: "1.2.1"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

healthCheck:
  liveness:
    path: /rate?from=PLAIN&to=CHOKOLATE
    initialDelaySeconds: 5
    periodSeconds: 10
  readiness:
    path: /rate?from=PLAIN&to=CHOKOLATE
    initialDelaySeconds: 2
    periodSeconds: 5

tracing:
  zipkinEndpoint: http://zipkin.monitoring.svc.cluster.local:9411/api/v2/spans